// <auto-generated />
using System;
using LMS.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411201528_AddCiftciRoleAndSeed")]
    partial class AddCiftciRoleAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LMS.Shared.Entities.Ciftci", b =>
                {
                    b.Property<int>("CiftciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiftciID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Adres")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TCKimlikNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CiftciID");

                    b.ToTable("Ciftci", (string)null);

                    b.HasData(
                        new
                        {
                            CiftciID = 1,
                            Ad = "Sistem",
                            KayitTarihi = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Soyad = "Çiftçisi"
                        });
                });

            modelBuilder.Entity("LMS.Shared.Entities.Hayvan", b =>
                {
                    b.Property<int>("HayvanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HayvanID"));

                    b.Property<int?>("AhirID")
                        .HasColumnType("int");

                    b.Property<int?>("AnneID")
                        .HasColumnType("int");

                    b.Property<int>("CiftciID")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HayvanDurumID")
                        .HasColumnType("int");

                    b.Property<int?>("IrkID")
                        .HasColumnType("int");

                    b.Property<string>("KupeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("HayvanID");

                    b.HasIndex("CiftciID");

                    b.ToTable("Hayvan", (string)null);
                });

            modelBuilder.Entity("LMS.Shared.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int?>("BagliCiftciID")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.HasIndex("BagliCiftciID");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanici", (string)null);
                });

            modelBuilder.Entity("LMS.Shared.Entities.Hayvan", b =>
                {
                    b.HasOne("LMS.Shared.Entities.Ciftci", "Ciftci")
                        .WithMany("Hayvanlar")
                        .HasForeignKey("CiftciID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ciftci");
                });

            modelBuilder.Entity("LMS.Shared.Entities.Kullanici", b =>
                {
                    b.HasOne("LMS.Shared.Entities.Ciftci", "BagliCiftci")
                        .WithMany()
                        .HasForeignKey("BagliCiftciID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BagliCiftci");
                });

            modelBuilder.Entity("LMS.Shared.Entities.Ciftci", b =>
                {
                    b.Navigation("Hayvanlar");
                });
#pragma warning restore 612, 618
        }
    }
}
